
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASIGN ATE DATE DAY ID INTAKE KCAL LIMIT NUMBER SUM\n    expresion : kcal_expr\n              | ate_expr\n              | average_intake\n              | limit\n              | sum_day\n    expresion : NUMBERexpresion : IDlimit : LIMIT NUMBERate_expr : ATE NUMBER IDkcal_expr : KCAL ID kcal_expr : KCAL ID ASIGN NUMBERaverage_intake : INTAKEsum_day : SUM DAY DATE'
    
_lr_action_items = {'NUMBER':([0,10,12,18,],[7,15,16,21,]),'ID':([0,9,15,],[8,14,19,]),'KCAL':([0,],[9,]),'ATE':([0,],[10,]),'INTAKE':([0,],[11,]),'LIMIT':([0,],[12,]),'SUM':([0,],[13,]),'$end':([1,2,3,4,5,6,7,8,11,14,16,19,20,21,],[0,-1,-2,-3,-4,-5,-6,-7,-12,-10,-8,-9,-13,-11,]),'DAY':([13,],[17,]),'ASIGN':([14,],[18,]),'DATE':([17,],[20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expresion':([0,],[1,]),'kcal_expr':([0,],[2,]),'ate_expr':([0,],[3,]),'average_intake':([0,],[4,]),'limit':([0,],[5,]),'sum_day':([0,],[6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expresion","S'",1,None,None,None),
  ('expresion -> kcal_expr','expresion',1,'p_expresion','calorease.py',184),
  ('expresion -> ate_expr','expresion',1,'p_expresion','calorease.py',185),
  ('expresion -> average_intake','expresion',1,'p_expresion','calorease.py',186),
  ('expresion -> limit','expresion',1,'p_expresion','calorease.py',187),
  ('expresion -> sum_day','expresion',1,'p_expresion','calorease.py',188),
  ('expresion -> NUMBER','expresion',1,'p_expr_numero','calorease.py',192),
  ('expresion -> ID','expresion',1,'p_expr_id','calorease.py',196),
  ('limit -> LIMIT NUMBER','limit',2,'p_limit','calorease.py',209),
  ('ate_expr -> ATE NUMBER ID','ate_expr',3,'p_expr_ate','calorease.py',217),
  ('kcal_expr -> KCAL ID','kcal_expr',2,'p_kcal_expr','calorease.py',245),
  ('kcal_expr -> KCAL ID ASIGN NUMBER','kcal_expr',4,'p_registro_consumo','calorease.py',262),
  ('average_intake -> INTAKE','average_intake',1,'p_average_intake','calorease.py',273),
  ('sum_day -> SUM DAY DATE','sum_day',3,'p_sum_day','calorease.py',286),
]
